name: CICD Pipeline for Python Application using github actions. 

on:
  push:
    branches: [ "main" ]
jobs:
  build: 
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install flake8 pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r requirements.txt
    - name: Install Trivy
      #shell: bash
      run: |
            sudo DEBIAN_FRONTEND=noninteractive apt-get install wget -y apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo DEBIAN_FRONTEND=noninteractive apt-get update -y
            sudo DEBIAN_FRONTEND=noninteractive apt-get install trivy -y
    - name: Trivy Scan
     # run: trivy fs . 
      run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
  Test:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Test
      run: python3 app.py
    
